export type IconId =
  'arrow-down-solid' |
  'arrow-left-solid' |
  'arrow-left' |
  'arrow-narrow-left-solid' |
  'arrow-narrow-left' |
  'arrow-narrow-right-solid' |
  'arrow-narrow-right' |
  'arrow-right' |
  'arrow-sm-right-solid' |
  'arrow-up-solid' |
  'arrow-up' |
  'arrows-expand' |
  'burger-menu' |
  'calendar' |
  'camera' |
  'caret-left' |
  'caret-right' |
  'chat' |
  'check-circle-solid' |
  'check-circle' |
  'check' |
  'chevron-down' |
  'chevron-left-solid' |
  'chevron-left' |
  'chevron-right-circle' |
  'chevron-right-solid' |
  'chevron-right' |
  'chevron-up' |
  'clic' |
  'clock' |
  'close' |
  'cloud-download' |
  'cloud-upload-solid' |
  'control-panel' |
  'cookies' |
  'document-text' |
  'double-chevron-left' |
  'double-chevron-right' |
  'download' |
  'emoji-happy' |
  'exclamation-circle-solid' |
  'eye' |
  'facebook' |
  'favorite-star' |
  'filter' |
  'fingerprint' |
  'gps' |
  'grid' |
  'home' |
  'laptop' |
  'light' |
  'like' |
  'linkedin' |
  'locator' |
  'lock' |
  'mail-solid' |
  'mail' |
  'minus-circle' |
  'minus' |
  'moon' |
  'phone' |
  'photo-camera' |
  'picture' |
  'play' |
  'plus' |
  'question-mark-circle-solid' |
  'question-mark-circle' |
  'search' |
  'switch-vertical' |
  'sync' |
  'trash' |
  'twitter' |
  'upload' |
  'user-circle' |
  'user' |
  'video-camera' |
  'volume-off' |
  'volume-up' |
  'whatsapp' |
  'x-solid' |
  'x' |
  'youtube';
